CI: debug toolchain

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -33,13 +33,11 @@ jobs:
           -o toolchain.tar.xz
         mkdir -p toolchain
         tar -xf toolchain.tar.xz -C toolchain
-        
+
     - name: Debug toolchain contents
       run: |
-        echo "Listing toolchain/bin:"
-        ls -la "${{ github.workspace }}/toolchain/bin" || echo "Dir not found or empty"
         echo "Listing toolchain:"
-        ls -R "${{ github.workspace }}/toolchain"
+        ls -la "${{ github.workspace }}/toolchain" || echo "Dir not found or empty"
 
     - name: Add ARM toolchain to PATH
       run: echo "${{ github.workspace }}/toolchain/bin" >> $GITHUB_PATH
